package com.oai.harmonywake;
import android.app.*;import android.content.*;import android.content.pm.*;import android.os.*;import android.provider.Settings;import android.widget.*;import java.util.*;
public class MainActivity extends Activity { LinearLayout list; List<WakeTask> tasks=new ArrayList<>();
protected void onCreate(Bundle b){super.onCreate(b);build();} protected void onResume(){super.onResume();tasks=TaskStore.load(this);render();}
TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setPadding(0,12,0,12);return v;} Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
void build(){ScrollView sv=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(36,36,36,36);sv.addView(r);r.addView(tv("Harmony Wake",28));r.addView(tv("定点唤醒指定 App，并按任务保持亮屏",15));Button add=btn("＋ 添加唤醒任务");add.setOnClickListener(v->edit(null));r.addView(add);Button st=btn("应用后台设置");st.setOnClickListener(v->{try{Intent i=new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,android.net.Uri.parse("package:"+getPackageName()));startActivity(i);}catch(Exception e){}});r.addView(st);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);r.addView(list);setContentView(sv);}
void render(){list.removeAllViews();if(tasks.isEmpty()){list.addView(tv("还没有任务。请添加至少两个时间点。",17));return;}tasks.sort((a,b)->a.hour*60+a.minute-(b.hour*60+b.minute));for(WakeTask t:new ArrayList<>(tasks)){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(12,18,12,18);c.addView(tv(String.format(Locale.getDefault(),"%02d:%02d",t.hour,t.minute),26));String a=t.appName.isEmpty()?t.packageName:t.appName;c.addView(tv("目标 App："+(a.isEmpty()?"未选择":a)+"
亮屏："+t.screenMinutes+" 分钟",16));Switch sw=new Switch(this);sw.setText("启用任务");sw.setChecked(t.enabled);sw.setOnCheckedChangeListener((x,on)->{t.enabled=on;persist();});c.addView(sw);LinearLayout row=new LinearLayout(this);Button e=btn("编辑");e.setOnClickListener(v->edit(t));row.addView(e);Button test=btn("立即测试");test.setOnClickListener(v->sendBroadcast(new Intent(this,AlarmReceiver.class).putExtra("task_id",t.id)));row.addView(test);Button del=btn("删除");del.setOnClickListener(v->{AlarmScheduler.cancel(this,t.id);tasks.remove(t);persist();render();});row.addView(del);c.addView(row);list.addView(c);}}
void edit(WakeTask old){WakeTask d=old==null?new WakeTask((int)(System.currentTimeMillis()&0x7fffffff),7,30,"","",10,true):new WakeTask(old.id,old.hour,old.minute,old.packageName,old.appName,old.screenMinutes,old.enabled);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);Button time=btn(String.format(Locale.getDefault(),"时间：%02d:%02d",d.hour,d.minute));time.setOnClickListener(v->new TimePickerDialog(this,(p,h,m)->{d.hour=h;d.minute=m;time.setText(String.format(Locale.getDefault(),"时间：%02d:%02d",h,m));},d.hour,d.minute,true).show());box.addView(time);Button app=btn(d.appName.isEmpty()?"选择目标 App":"目标 App："+d.appName);app.setOnClickListener(v->choose(d,app));box.addView(app);EditText mins=new EditText(this);mins.setInputType(2);mins.setHint("亮屏分钟数");mins.setText(String.valueOf(d.screenMinutes));box.addView(mins);new AlertDialog.Builder(this).setTitle(old==null?"添加任务":"编辑任务").setView(box).setPositiveButton("保存",(x,w)->{try{d.screenMinutes=Math.max(1,Integer.parseInt(mins.getText().toString().trim()));}catch(Exception q){d.screenMinutes=10;}if(old==null)tasks.add(d);else{int k=tasks.indexOf(old);if(k>=0)tasks.set(k,d);}persist();render();}).setNegativeButton("取消",null).show();}
void choose(WakeTask d,Button b){PackageManager pm=getPackageManager();List<ApplicationInfo> apps=new ArrayList<>();for(ApplicationInfo a:pm.getInstalledApplications(0))if(pm.getLaunchIntentForPackage(a.packageName)!=null&&!a.packageName.equals(getPackageName()))apps.add(a);apps.sort(Comparator.comparing(a->pm.getApplicationLabel(a).toString().toLowerCase()));String[] labels=new String[apps.size()];for(int i=0;i<apps.size();i++)labels[i]=pm.getApplicationLabel(apps.get(i)).toString();new AlertDialog.Builder(this).setTitle("选择目标 App").setItems(labels,(x,i)->{ApplicationInfo a=apps.get(i);d.packageName=a.packageName;d.appName=pm.getApplicationLabel(a).toString();b.setText("目标 App："+d.appName);}).show();}
void persist(){TaskStore.save(this,tasks);for(WakeTask t:tasks)AlarmScheduler.schedule(this,t);} }
